### PR TITLE
tweaks spree

### PR DESCRIPTION
**Pull request by AntonioMeireles**
- ~~add the ability to run arbitrary CoreOS versions and channels~~(#22).
- ~~add a note on the docs about current VirtualBox woes~~ (#20).
- ~~add the ability to customize VM's memory~~(#26).
- ~~add the ability to customize cloud-config's location~~(#27).
- ~~make gpg verification optional~~(#21).
- ~~update documentation to reflect ongoing tweak spree~~.
- ~~share /Users by default~~(#31).
- ~~add 'static' IP support~~(#28).
- ~~pass VMs IP address to host~~(#31).
- ~~allow to pragmatically pass the ssh public key~~(#29).

### CODE REVIEW

**Comment by bakins** [comment]
`getVersionID` requires you to have internet connectivity even if you already have all the bits downloaded. One of my common use cases for vagrant, etc, is to work while not being connected.

**Comment by rimusz** [comment]
@bakins yes you are right, we should pre download all images and then on run we just use them, as Internet connection should not be necessity for the run command.

**Comment by AntonioMeireles** [comment]
@bakins - very good point. i hope that the latest iteration addresses your concerns.

**Comment by bakins** [comment]
Sorry to be a pain, but will you split these into separate PRs?  The fetch logic in one, NFS in another, and other tweaks in another. I'd like to merge the fetch logic, but think the NFS needs a bit of tweaking before we merge. Overall looks good, but like to merge one "concept" per PR.

**Comment by AntonioMeireles** [comment]
@bakins no pain at all, will do. will reference this issue, keeping it open, on each _forked_ PR, until list empty or individual feature deemed not worthwile.

**Comment by bakins** [comment]
@AntonioMeireles Thanks!

**Comment by AntonioMeireles** [comment]
@bakins when you have time please look at PRs _2{0,1,2,3}_. after that, i'll keep _forking_ the remaining stuff :smile:.

**Comment by AntonioMeireles** [comment]
closing this as everything now split in separate PRs.

**Pull request closed without merging**
