### PR TITLE
share /Users by default and pass VMs IP address to host.

### PR DESCRIPTION
**Pull request by AntonioMeireles**
forked from #13 and on top of #37. 

from @bakins comments on #13 this seemed to be most tricky item. at sight, this was the cleanest, least intrusive, way to achieve the desired functionality i could think of.

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
rebased, for review.

**Comment by chancez** [comment]
@AntonioMeireles Would you mind rebasing so you only have the last commit? Otherwise I think I'll just re-open a PR that's got that commit alone.

**Comment by AntonioMeireles** [comment]
just rebased. :smile:

**Comment by AntonioMeireles** [comment]
@philips, et al. 

TimeOuting. action ongoing at [github.com/TheNewNormal/corectl](github.com/TheNewNormal/corectl)

**Pull request closed without merging**
