### PR TITLE
update warning regarding VirtualBox now that vbox 5.0 is out.

### PR DESCRIPTION
**Pull request by AntonioMeireles**
looks like vbox 5 fixed its obnoxious behavior (at least i'm unable to trigger crashes anymore :smile: ) so README updated accordingly.

(on top of #36)

### CODE REVIEW

**Comment by rimusz** [comment]
vbox 5 and xhyve can be run at the same time :)

**Comment by bakins** [comment]
rebase on current master and I'll merge.

**Comment by AntonioMeireles** [comment]
just rebased.

**Comment by bakins** [comment]
This has #34 and #36 in it, so looks like you rebased against a different branch rather than master?

**Comment by AntonioMeireles** [comment]
rebased against plain upstream/master. (&& thanks for your patience)

**Comment by chancez** [comment]
LGTM

**Pull request merged**
