### PR TITLE
add the ability to pragmatically pass the ssh public key.

### PR DESCRIPTION
**Pull request by AntonioMeireles**
- on top of #26, #27 and #28 

(forked from coreos/coreos-xhyve#13)

### CODE REVIEW

**Comment by bakins** [comment]
Is `SSHKEY` expected to be the actual public key or path to a file? Perhaps need to document usage more.

**Comment by AntonioMeireles** [comment]
actual public key as path to file would end need extra logic (as a single file could well have more than one public key).  renasing and updating usage in a bit. && thanks!

**Comment by bakins** [comment]
Let's update docs in another PR.

**Comment by AntonioMeireles** [comment]
ok.

**Pull request merged**
