### PR TITLE
add the ability to pragmatically pass to xhyve whatever parameters we want.

### PR DESCRIPTION
**Pull request by AntonioMeireles**

### CODE REVIEW

**Comment by bakins** [comment]
rebase on current master and I'll merge.

**Comment by AntonioMeireles** [comment]
just rebased.

**Comment by bakins** [comment]
This has #34 in it, so looks like you rebased against that rather than master?

**Comment by AntonioMeireles** [comment]
ok, now _really_ rebased against upstream/master :smile:

**Comment by chancez** [comment]
LGTM

**Pull request merged**
