### PR TITLE
use sudo by default (spares a few clicks in each run).

### PR DESCRIPTION
**Pull request by AntonioMeireles**

### CODE REVIEW

**Comment by bakins** [comment]
I'd rather user need to explicitly call `sudo`. 
@philips thoughts?

**Comment by AntonioMeireles** [comment]
on hold, pending review. FWIW and albeit i dislike SUID like stuff given that atm we need root elevation to get networking (and without networking all this not that usefull) it makes sense (at least for me) in this specific case to 'elevate' transparently by default.

**Comment by chancez** [comment]
This might be nice, because if you run export variables before running sudo, then sudo clears them. SO you need to run things like `sudo CPU=2 ./coreos-xhyve` rather than `export CPU=2; sudo ./coreos-xhyve`.

But still, it's a security concern.

**Comment by AntonioMeireles** [comment]
@philips, et al. 

TimeOuting. action ongoing at [github.com/TheNewNormal/corectl](github.com/TheNewNormal/corectl)

**Pull request closed without merging**
