### PR TITLE
Update key

### PR DESCRIPTION
**Pull request by tt**
This updates [the key](https://coreos.com/security/image-signing-key/CoreOS_Image_Signing_Key.asc).

Executing `coreos-xhyve-fetch` would otherwise terminate:

```
...
gpg: Signature made Thu Sep 10 09:08:43 2015 CEST using RSA key ID 1CB5FA26
gpg: Can't check signature: public key not found
```

### CODE REVIEW

**Comment by c4milo** [comment]
yes please, I ran into this issue too.

**Comment by c4milo** [comment]
looks like this one is a duplicated of https://github.com/coreos/coreos-xhyve/pull/46

**Comment by tt** [comment]
Can you merge either of these, @ecnahc515 or @philips?

**Comment by chancez** [comment]
I merged #46, so I'm closing this.

**Comment by tt** [comment]
Thank you.

**Pull request closed without merging**
